name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore Numbers.Tests/Numbers.Tests.csproj
    - name: Build
      run: dotnet build Numbers.Tests/Numbers.Tests.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test Numbers.Tests/Numbers.Tests.csproj --no-restore --verbosity normal
